---
title: "Math Pinpoint Correlation Analysis"
description: |
  The correlation matrix provides insights into the relationships between different mathematical skills by measuring how strongly they are associated with each other. These relationships are quantified on a scale from -1 to 1, where 1 indicates a perfect positive relationship (as one skill increases, the other increases proportionally), 0 indicates no relationship between skills, and -1 indicates a perfect negative relationship (as one skill increases, the other decreases proportionally).
author:
  - name: Saratessa Palos 
    url: 
    affiliation: University of Oregon, FIT Learning 
    affiliation_url: 
date: 02-25-2025
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(here)
```
```{r}

```


